dist: xenial
os: linux
language: node_js
node_js:
  - 14

services:
  - mongodb

install:
  - curl https://install.meteor.com | /bin/sh
  - meteor npm i
  - meteor build .build --directory --debug
  - cd .build/bundle/programs/server && npm install && cd ../../../..

script:
  - MONGO_URL=mongodb://127.0.0.1 ROOT_URL=http://localhost:3000 PORT=3000 node /home/travis/build/StrictlySkyler/harbormaster/.build/bundle/main.js &
  - npm run test:e2e
