version: '3.6'

services:

  harbormaster:
    image: strictlyskyler/harbormaster:1.10.1
    ports:
      - "3000:80"
    container_name: harbormaster
    hostname: harbormaster
    environment:
      # Required:
      MONGO_URL: ${MONGO_URL}
      ROOT_URL: ${ROOT_URL}
      PORT: 80
      # Optional:
      KADIRA_APP_ID: ${KADIRA_APP_ID}
      KADIRA_APP_SECRET: ${KADIRA_APP_SECRET}
      KADIRA_OPTIONS_ENDPOINT: ${KADIRA_OPTIONS_ENDPOINT}
      MAIL_URL: ${MAIL_URL}
      DEBUG: ${DEBUG}
    volumes:
      - ~/.harbormaster:/root/.harbormaster
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
